# Generated by Django 5.2.8 on 2025-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('NG', 'Nigeria'), ('ZA', 'South Africa'), ('UG', 'Uganda'), ('GH', 'Ghana'), ('TZ', 'Tanzania'), ('RW', 'Rwanda')], max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('languages', models.CharField(default='English', max_length=100)),
                ('is_24_7', models.BooleanField(default=True)),
                ('category', models.CharField(default='GBV Hotline', max_length=50)),
            ],
        ),
    ]
