# Generated by Django 5.2.8 on 2025-11-28 17:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_violence', models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('emotional', 'Emotional/Psychological'), ('economic', 'Economic/Financial'), ('stalking', 'Stalking/Harassment'), ('digital', 'Digital/Online Abuse')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('perpetrator_relation', models.CharField(blank=True, choices=[('partner', 'Current/Former Partner'), ('family', 'Family Member'), ('friend', 'Friend/Acquaintance'), ('colleague', 'Colleague/Boss'), ('stranger', 'Stranger'), ('other', 'Other')], max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical - Immediate Danger')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated to Hotline')], default='pending', max_length=20)),
                ('retention_expiry', models.DateTimeField(default=datetime.datetime(2026, 2, 26, 17, 47, 6, 773782, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reports.report')),
            ],
        ),
    ]
