# Generated by Django 5.2.8 on 2025-11-28 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='retention_expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 17, 59, 57, 668867, tzinfo=datetime.timezone.utc)),
        ),
    ]
