# Generated by Django 5.2.8 on 2025-11-28 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_retention_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='retention_expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 21, 39, 29, 888696, tzinfo=datetime.timezone.utc)),
        ),
    ]
