# Generated by Django 5.2.8 on 2025-11-28 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('toxicity_score', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(choices=[('safe', 'Safe'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], default='safe', max_length=10)),
                ('labels', models.JSONField(default=list)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
